db_config: &db_config
  adapter: mysql2
  host: 127.0.0.1
  strict: true
  port: <%= (ENV['DUAL_ENV'] == 'setup') ? ENV.fetch('PS_S0_SETUP_PORT') {7002} : ENV.fetch('PS_S0_MAIN_PORT') {7001} %>
  reconnect: true
  automatic_close: false
  ssl_mode: :disabled
  sslverify: false

# Set login credentials
login: &login
  username: root
  password: password

development:
  <<: *db_config
  <<: *login
  database: short_link_develop

test:
  <<: *db_config
  <<: *login
  database: short_link_test